[package]
name = "paint-2d"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["RandomSearch"]
description = "A fun, two-dimensional painting app that runs in your terminal"

[dependencies]
crossterm = "0.28.1"
ctrlc = "3.4.5"
